package bd2.util;

import java.text.SimpleDateFormat;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;
import org.hibernate.tool.hbm2ddl.SchemaExport;

import bd2.model.Pizarra;
import bd2.model.Proyecto;
import bd2.model.Sitio;
import bd2.model.TareaDeDesarrollo;
import bd2.model.TareaDeInvestigacion;
import bd2.model.Usuario;

public class DBLoader {

	private static SessionFactory sessions;
		
	public DBLoader() { }

	public static void main(String[] args) {
		try {
			System.out.println("----------------------- Setting up Hibernate -----------------------");
			Configuration cfg = new Configuration();
			cfg.configure("hibernate/hibernate.cfg.xml");

			System.out.println("Droping schema.........");
			new SchemaExport(cfg).drop(true, true);
			System.out.println("DONE.");

			System.out.println("Generating schema.........");
			new SchemaExport(cfg).create(true, true);
			System.out.println("DONE.");

			System.out.println("Building sessions.........");
			sessions = cfg.buildSessionFactory();
			Sitio sitio = cargarBase();
			
			Session session = sessions.openSession();
			Transaction tx = null;
			try {
				tx = session.beginTransaction();
				session.save(sitio);
				session.flush();
				tx.commit();
			} catch (Exception e) {
				e.printStackTrace();
				if (tx != null) {
					tx.rollback();
				}
				session.close();
			}
			session.disconnect();
			
			System.out.println("DONE.");
		} catch (Exception e) {
			System.out.println("------------------------FAIL.------------------------");
			e.printStackTrace();
		}
	}

	private static Sitio cargarBase() throws Exception {
		SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
		
		Sitio sitio = new Sitio();
		Usuario achim = new Usuario("achim@pizarrello.net", "Achim");
		sitio.registrarUsuario(achim);
		Usuario adolf = new Usuario("adolf@pizarrello.net", "Adolf");
		sitio.registrarUsuario(adolf);
		Usuario albrecht = new Usuario("albrecht@pizarrello.net", "Albrecht");
		sitio.registrarUsuario(albrecht);
		Usuario alexander = new Usuario("alexander@pizarrello.net", "Alexander");
		sitio.registrarUsuario(alexander);
		Usuario alois = new Usuario("alois@pizarrello.net", "Alois");
		sitio.registrarUsuario(alois);
		Usuario ambros = new Usuario("ambros@pizarrello.net", "Ambros");
		sitio.registrarUsuario(ambros);
		Usuario andreas = new Usuario("andreas@pizarrello.net", "Andreas");
		sitio.registrarUsuario(andreas);
		Usuario anselm = new Usuario("anselm@pizarrello.net", "Anselm");
		sitio.registrarUsuario(anselm);
		Usuario anton = new Usuario("anton@pizarrello.net", "Anton");
		sitio.registrarUsuario(anton);
		Usuario armin = new Usuario("armin@pizarrello.net", "Armin");
		sitio.registrarUsuario(armin);
		Usuario arnd = new Usuario("arnd@pizarrello.net", "Arnd");
		sitio.registrarUsuario(arnd);
		Usuario arno = new Usuario("arno@pizarrello.net", "Arno");
		sitio.registrarUsuario(arno);
		Usuario arnold = new Usuario("arnold@pizarrello.net", "Arnold");
		sitio.registrarUsuario(arnold);
		Usuario arnulf = new Usuario("arnulf@pizarrello.net", "Arnulf");
		sitio.registrarUsuario(arnulf);
		Usuario augustus = new Usuario("augustus@pizarrello.net", "Augustus");
		sitio.registrarUsuario(augustus);
		Usuario axel = new Usuario("axel@pizarrello.net", "Axel");
		sitio.registrarUsuario(axel);
		Usuario benjamin = new Usuario("benjamin@pizarrello.net", "Benjamin");
		sitio.registrarUsuario(benjamin);
		Usuario bernd = new Usuario("bernd@pizarrello.net", "Bernd");
		sitio.registrarUsuario(bernd);
		Usuario bernhard = new Usuario("bernhard@pizarrello.net", "Bernhard");
		sitio.registrarUsuario(bernhard);
		Usuario berthold = new Usuario("berthold@pizarrello.net", "Berthold");
		sitio.registrarUsuario(berthold);
		Usuario bodo = new Usuario("bodo@pizarrello.net", "Bodo");
		sitio.registrarUsuario(bodo);
		Usuario bruno = new Usuario("bruno@pizarrello.net", "Bruno");
		sitio.registrarUsuario(bruno);
		Usuario carsten = new Usuario("carsten@pizarrello.net", "Carsten");
		sitio.registrarUsuario(carsten);
		Usuario christian = new Usuario("christian@pizarrello.net", "Christian");
		sitio.registrarUsuario(christian);
		Usuario christof = new Usuario("christof@pizarrello.net", "Christof");
		sitio.registrarUsuario(christof);
		Usuario clemens = new Usuario("clemens@pizarrello.net", "Clemens");
		sitio.registrarUsuario(clemens);
		Usuario conrad = new Usuario("conrad@pizarrello.net", "Conrad");
		sitio.registrarUsuario(conrad);
		Usuario curd = new Usuario("curd@pizarrello.net", "Curd");
		sitio.registrarUsuario(curd);
		Usuario dagobert = new Usuario("dagobert@pizarrello.net", "Dagobert");
		sitio.registrarUsuario(dagobert);
		Usuario detlef = new Usuario("detlef@pizarrello.net", "Detlef");
		sitio.registrarUsuario(detlef);
		Usuario dieter = new Usuario("dieter@pizarrello.net", "Dieter");
		sitio.registrarUsuario(dieter);
		Usuario dietrich = new Usuario("dietrich@pizarrello.net", "Dietrich");
		sitio.registrarUsuario(dietrich);
		Usuario dierk = new Usuario("dierk@pizarrello.net", "Dierk");
		sitio.registrarUsuario(dierk);
		Usuario dolf = new Usuario("dolf@pizarrello.net", "Dolf");
		sitio.registrarUsuario(dolf);
		Usuario dominik = new Usuario("dominik@pizarrello.net", "Dominik");
		sitio.registrarUsuario(dominik);
		Usuario egon = new Usuario("egon@pizarrello.net", "Egon");
		sitio.registrarUsuario(egon);
		Usuario elias = new Usuario("elias@pizarrello.net", "Elias");
		sitio.registrarUsuario(elias);
		Usuario elmar = new Usuario("elmar@pizarrello.net", "Elmar");
		sitio.registrarUsuario(elmar);
		Usuario emil = new Usuario("emil@pizarrello.net", "Emil");
		sitio.registrarUsuario(emil);
		Usuario emmerich = new Usuario("emmerich@pizarrello.net", "Emmerich");
		sitio.registrarUsuario(emmerich);
		Usuario engelbert = new Usuario("engelbert@pizarrello.net", "Engelbert");
		sitio.registrarUsuario(engelbert);
		Usuario erhard = new Usuario("erhard@pizarrello.net", "Erhard");
		sitio.registrarUsuario(erhard);
		Usuario erich = new Usuario("erich@pizarrello.net", "Erich");
		sitio.registrarUsuario(erich);
		Usuario ernst = new Usuario("ernst@pizarrello.net", "Ernst");
		sitio.registrarUsuario(ernst);
		Usuario erwin = new Usuario("erwin@pizarrello.net", "Erwin");
		sitio.registrarUsuario(erwin);
		Usuario eugen = new Usuario("eugen@pizarrello.net", "Eugen");
		sitio.registrarUsuario(eugen);
		Usuario ewald = new Usuario("ewald@pizarrello.net", "Ewald");
		sitio.registrarUsuario(ewald);
		Usuario fabian = new Usuario("fabian@pizarrello.net", "Fabian");
		sitio.registrarUsuario(fabian);
		Usuario falco = new Usuario("falco@pizarrello.net", "Falco");
		sitio.registrarUsuario(falco);
		Usuario felix = new Usuario("felix@pizarrello.net", "Felix");
		sitio.registrarUsuario(felix);
		Usuario ferdinand = new Usuario("ferdinand@pizarrello.net", "Ferdinand");
		sitio.registrarUsuario(ferdinand);
		Usuario florian = new Usuario("florian@pizarrello.net", "Florian");
		sitio.registrarUsuario(florian);
		Usuario franz = new Usuario("franz@pizarrello.net", "Franz");
		sitio.registrarUsuario(franz);
		Usuario friedhelm = new Usuario("friedhelm@pizarrello.net", "Friedhelm");
		sitio.registrarUsuario(friedhelm);
		Usuario friedrich = new Usuario("friedrich@pizarrello.net", "Friedrich");
		sitio.registrarUsuario(friedrich);
		Usuario fritz = new Usuario("fritz@pizarrello.net", "Fritz");
		sitio.registrarUsuario(fritz);
		Usuario gebhard = new Usuario("gebhard@pizarrello.net", "Gebhard");
		sitio.registrarUsuario(gebhard);
		Usuario georg = new Usuario("georg@pizarrello.net", "Georg");
		sitio.registrarUsuario(georg);
		Usuario gerhard = new Usuario("gerhard@pizarrello.net", "Gerhard");
		sitio.registrarUsuario(gerhard);
		Usuario gernot = new Usuario("gernot@pizarrello.net", "Gernot");
		sitio.registrarUsuario(gernot);
		Usuario golo = new Usuario("golo@pizarrello.net", "Golo");
		sitio.registrarUsuario(golo);
		Usuario gottfried = new Usuario("gottfried@pizarrello.net", "Gottfried");
		sitio.registrarUsuario(gottfried);
		Usuario gotthold = new Usuario("gotthold@pizarrello.net", "Gotthold");
		sitio.registrarUsuario(gotthold);
		Usuario gottlieb = new Usuario("gottlieb@pizarrello.net", "Gottlieb");
		sitio.registrarUsuario(gottlieb);
		Usuario gregor = new Usuario("gregor@pizarrello.net", "Gregor");
		sitio.registrarUsuario(gregor);
		Usuario gunther = new Usuario("gunther@pizarrello.net", "Gunther");
		sitio.registrarUsuario(gunther);
		Usuario gustaf = new Usuario("gustaf@pizarrello.net", "Gustaf");
		sitio.registrarUsuario(gustaf);
		Usuario hans = new Usuario("hans@pizarrello.net", "Hans");
		sitio.registrarUsuario(hans);
		Usuario harald = new Usuario("harald@pizarrello.net", "Harald");
		sitio.registrarUsuario(harald);
		Usuario hartmut = new Usuario("hartmut@pizarrello.net", "Hartmut");
		sitio.registrarUsuario(hartmut);
		Usuario hartwig = new Usuario("hartwig@pizarrello.net", "Hartwig");
		sitio.registrarUsuario(hartwig);
		Usuario heiner = new Usuario("heiner@pizarrello.net", "Heiner");
		sitio.registrarUsuario(heiner);
		Usuario heinrich = new Usuario("heinrich@pizarrello.net", "Heinrich");
		sitio.registrarUsuario(heinrich);
		Usuario heinz = new Usuario("heinz@pizarrello.net", "Heinz");
		sitio.registrarUsuario(heinz);
		Usuario helge = new Usuario("helge@pizarrello.net", "Helge");
		sitio.registrarUsuario(helge);
		Usuario helmut = new Usuario("helmut@pizarrello.net", "Helmut");
		sitio.registrarUsuario(helmut);
		Usuario herbert = new Usuario("herbert@pizarrello.net", "Herbert");
		sitio.registrarUsuario(herbert);
		Usuario hildebrand = new Usuario("hildebrand@pizarrello.net", "Hildebrand");
		sitio.registrarUsuario(hildebrand);
		Usuario holger = new Usuario("holger@pizarrello.net", "Holger");
		sitio.registrarUsuario(holger);
		Usuario horst = new Usuario("horst@pizarrello.net", "Horst");
		sitio.registrarUsuario(horst);
		Usuario hugbert = new Usuario("hugbert@pizarrello.net", "Hugbert");
		sitio.registrarUsuario(hugbert);
		Usuario hugo = new Usuario("hugo@pizarrello.net", "Hugo");
		sitio.registrarUsuario(hugo);
		Usuario ignatius = new Usuario("ignatius@pizarrello.net", "Ignatius");
		sitio.registrarUsuario(ignatius);
		Usuario ingemar = new Usuario("ingemar@pizarrello.net", "Ingemar");
		sitio.registrarUsuario(ingemar);
		Usuario jan = new Usuario("jan@pizarrello.net", "Jan");
		sitio.registrarUsuario(jan);
		Usuario jens = new Usuario("jens@pizarrello.net", "Jens");
		sitio.registrarUsuario(jens);
		Usuario joachim = new Usuario("joachim@pizarrello.net", "Joachim");
		sitio.registrarUsuario(joachim);
		Usuario johann = new Usuario("johann@pizarrello.net", "Johann");
		sitio.registrarUsuario(johann);
		Usuario johannes = new Usuario("johannes@pizarrello.net", "Johannes");
		sitio.registrarUsuario(johannes);
		Usuario jonas = new Usuario("jonas@pizarrello.net", "Jonas");
		sitio.registrarUsuario(jonas);
		Usuario jorg = new Usuario("jorg@pizarrello.net", "Jorg");
		sitio.registrarUsuario(jorg);
		Usuario jurgen = new Usuario("jurgen@pizarrello.net", "Jurgen");
		sitio.registrarUsuario(jurgen);
		Usuario karl = new Usuario("karl@pizarrello.net", "Karl");
		sitio.registrarUsuario(karl);
		Usuario karlheinz = new Usuario("karlheinz@pizarrello.net", "Karlheinz");
		sitio.registrarUsuario(karlheinz);
		Usuario karsten = new Usuario("karsten@pizarrello.net", "Karsten");
		sitio.registrarUsuario(karsten);
		Usuario kaspar = new Usuario("kaspar@pizarrello.net", "Kaspar");
		sitio.registrarUsuario(kaspar);
		Usuario klaus = new Usuario("klaus@pizarrello.net", "Klaus");
		sitio.registrarUsuario(klaus);
		Usuario knut = new Usuario("knut@pizarrello.net", "Knut");
		sitio.registrarUsuario(knut);
		Usuario konrad = new Usuario("konrad@pizarrello.net", "Konrad");
		sitio.registrarUsuario(konrad);
		Usuario kristian = new Usuario("kristian@pizarrello.net", "Kristian");
		sitio.registrarUsuario(kristian);
		Usuario kristof = new Usuario("kristof@pizarrello.net", "Kristof");
		sitio.registrarUsuario(kristof);
		Usuario kurt = new Usuario("kurt@pizarrello.net", "Kurt");
		sitio.registrarUsuario(kurt);
		Usuario lars = new Usuario("lars@pizarrello.net", "Lars");
		sitio.registrarUsuario(lars);
		Usuario laurenz = new Usuario("laurenz@pizarrello.net", "Laurenz");
		sitio.registrarUsuario(laurenz);
		Usuario lenz = new Usuario("lenz@pizarrello.net", "Lenz");
		sitio.registrarUsuario(lenz);
		Usuario leon = new Usuario("leon@pizarrello.net", "Leon");
		sitio.registrarUsuario(leon);
		Usuario leonhard = new Usuario("leonhard@pizarrello.net", "Leonhard");
		sitio.registrarUsuario(leonhard);
		Usuario leopold = new Usuario("leopold@pizarrello.net", "Leopold");
		sitio.registrarUsuario(leopold);
		Usuario lothar = new Usuario("lothar@pizarrello.net", "Lothar");
		sitio.registrarUsuario(lothar);
		Usuario ludwig = new Usuario("ludwig@pizarrello.net", "Ludwig");
		sitio.registrarUsuario(ludwig);
		Usuario lukas = new Usuario("lukas@pizarrello.net", "Lukas");
		sitio.registrarUsuario(lukas);
		Usuario luther = new Usuario("luther@pizarrello.net", "Luther");
		sitio.registrarUsuario(luther);
		Usuario lutz = new Usuario("lutz@pizarrello.net", "Lutz");
		sitio.registrarUsuario(lutz);
		Usuario manfred = new Usuario("manfred@pizarrello.net", "Manfred");
		sitio.registrarUsuario(manfred);
		Usuario marcel = new Usuario("marcel@pizarrello.net", "Marcel");
		sitio.registrarUsuario(marcel);
		Usuario marco = new Usuario("marco@pizarrello.net", "Marco");
		sitio.registrarUsuario(marco);
		Usuario mario = new Usuario("mario@pizarrello.net", "Mario");
		sitio.registrarUsuario(mario);
		Usuario marius = new Usuario("marius@pizarrello.net", "Marius");
		sitio.registrarUsuario(marius);
		Usuario markus = new Usuario("markus@pizarrello.net", "Markus");
		sitio.registrarUsuario(markus);
		Usuario martin = new Usuario("martin@pizarrello.net", "Martin");
		sitio.registrarUsuario(martin);
		Usuario matthaus = new Usuario("matthaus@pizarrello.net", "Matthaus");
		sitio.registrarUsuario(matthaus);
		Usuario mathia = new Usuario("mathia@pizarrello.net", "Mathia");
		sitio.registrarUsuario(mathia);
		Usuario max = new Usuario("max@pizarrello.net", "Max");
		sitio.registrarUsuario(max);
		Usuario maximilian = new Usuario("maximilian@pizarrello.net", "Maximilian");
		sitio.registrarUsuario(maximilian);
		Usuario meinhard = new Usuario("meinhard@pizarrello.net", "Meinhard");
		sitio.registrarUsuario(meinhard);
		Usuario michael = new Usuario("michael@pizarrello.net", "Michael");
		sitio.registrarUsuario(michael);
		Usuario nikolaus = new Usuario("nikolaus@pizarrello.net", "Nikolaus");
		sitio.registrarUsuario(nikolaus);
		Usuario nils = new Usuario("nils@pizarrello.net", "Nils");
		sitio.registrarUsuario(nils);
		Usuario norbert = new Usuario("norbert@pizarrello.net", "Norbert");
		sitio.registrarUsuario(norbert);
		Usuario olof = new Usuario("olof@pizarrello.net", "Olof");
		sitio.registrarUsuario(olof);
		Usuario oskar = new Usuario("oskar@pizarrello.net", "Oskar");
		sitio.registrarUsuario(oskar);
		Usuario oswald = new Usuario("oswald@pizarrello.net", "Oswald");
		sitio.registrarUsuario(oswald);
		Usuario oswin = new Usuario("oswin@pizarrello.net", "Oswin");
		sitio.registrarUsuario(oswin);
		Usuario otto = new Usuario("otto@pizarrello.net", "Otto");
		sitio.registrarUsuario(otto);
		Usuario philipp = new Usuario("philipp@pizarrello.net", "Philipp");
		sitio.registrarUsuario(philipp);
		Usuario poldi = new Usuario("poldi@pizarrello.net", "Poldi");
		sitio.registrarUsuario(poldi);
		Usuario raimund = new Usuario("raimund@pizarrello.net", "Raimund");
		sitio.registrarUsuario(raimund);
		Usuario rainer = new Usuario("rainer@pizarrello.net", "Rainer");
		sitio.registrarUsuario(rainer);
		Usuario ralf = new Usuario("ralf@pizarrello.net", "Ralf");
		sitio.registrarUsuario(ralf);
		Usuario randolf = new Usuario("randolf@pizarrello.net", "Randolf");
		sitio.registrarUsuario(randolf);
		Usuario reinhard = new Usuario("reinhard@pizarrello.net", "Reinhard");
		sitio.registrarUsuario(reinhard);
		Usuario reinhold = new Usuario("reinhold@pizarrello.net", "Reinhold");
		sitio.registrarUsuario(reinhold);
		Usuario rené = new Usuario("rené@pizarrello.net", "René");
		sitio.registrarUsuario(rené);
		Usuario richard = new Usuario("richard@pizarrello.net", "Richard");
		sitio.registrarUsuario(richard);
		Usuario rudiger = new Usuario("rudiger@pizarrello.net", "Rudiger");
		sitio.registrarUsuario(rudiger);
		Usuario rudolf = new Usuario("rudolf@pizarrello.net", "Rudolf");
		sitio.registrarUsuario(rudolf);
		Usuario rupert = new Usuario("rupert@pizarrello.net", "Rupert");
		sitio.registrarUsuario(rupert);
		Usuario sabine = new Usuario("sabine@pizarrello.net", "Sabine");
		sitio.registrarUsuario(sabine);
		Usuario schorsch = new Usuario("schorsch@pizarrello.net", "Schorsch");
		sitio.registrarUsuario(schorsch);
		Usuario sebastian = new Usuario("sebastian@pizarrello.net", "Sebastian");
		sitio.registrarUsuario(sebastian);
		Usuario sepp = new Usuario("sepp@pizarrello.net", "Sepp");
		sitio.registrarUsuario(sepp);
		Usuario siegfried = new Usuario("siegfried@pizarrello.net", "Siegfried");
		sitio.registrarUsuario(siegfried);
		Usuario simon = new Usuario("simon@pizarrello.net", "Simon");
		sitio.registrarUsuario(simon);
		Usuario stefan = new Usuario("stefan@pizarrello.net", "Stefan");
		sitio.registrarUsuario(stefan);
		Usuario steffen = new Usuario("steffen@pizarrello.net", "Steffen");
		sitio.registrarUsuario(steffen);
		Usuario sven = new Usuario("sven@pizarrello.net", "Sven");
		sitio.registrarUsuario(sven);
		Usuario theodor = new Usuario("theodor@pizarrello.net", "Theodor");
		sitio.registrarUsuario(theodor);
		Usuario thomas = new Usuario("thomas@pizarrello.net", "Thomas");
		sitio.registrarUsuario(thomas);
		Usuario till = new Usuario("till@pizarrello.net", "Till");
		sitio.registrarUsuario(till);
		Usuario tim = new Usuario("tim@pizarrello.net", "Tim");
		sitio.registrarUsuario(tim);
		Usuario timo = new Usuario("timo@pizarrello.net", "Timo");
		sitio.registrarUsuario(timo);
		Usuario tobias = new Usuario("tobias@pizarrello.net", "Tobias");
		sitio.registrarUsuario(tobias);
		Usuario torsten = new Usuario("torsten@pizarrello.net", "Torsten");
		sitio.registrarUsuario(torsten);
		Usuario udo = new Usuario("udo@pizarrello.net", "Udo");
		sitio.registrarUsuario(udo);
		Usuario ulf = new Usuario("ulf@pizarrello.net", "Ulf");
		sitio.registrarUsuario(ulf);
		Usuario ulrich = new Usuario("ulrich@pizarrello.net", "Ulrich");
		sitio.registrarUsuario(ulrich);
		Usuario urban = new Usuario("urban@pizarrello.net", "Urban");
		sitio.registrarUsuario(urban);
		Usuario urs = new Usuario("urs@pizarrello.net", "Urs");
		sitio.registrarUsuario(urs);
		Usuario uwe = new Usuario("uwe@pizarrello.net", "Uwe");
		sitio.registrarUsuario(uwe);
		Usuario veit = new Usuario("veit@pizarrello.net", "Veit");
		sitio.registrarUsuario(veit);
		Usuario viktor = new Usuario("viktor@pizarrello.net", "Viktor");
		sitio.registrarUsuario(viktor);
		Usuario vinzenz = new Usuario("vinzenz@pizarrello.net", "Vinzenz");
		sitio.registrarUsuario(vinzenz);
		Usuario volkard = new Usuario("volkard@pizarrello.net", "Volkard");
		sitio.registrarUsuario(volkard);
		Usuario volker = new Usuario("volker@pizarrello.net", "Volker");
		sitio.registrarUsuario(volker);
		Usuario waldemar = new Usuario("waldemar@pizarrello.net", "Waldemar");
		sitio.registrarUsuario(waldemar);
		Usuario walther = new Usuario("walther@pizarrello.net", "Walther");
		sitio.registrarUsuario(walther);
		Usuario wendel = new Usuario("wendel@pizarrello.net", "Wendel");
		sitio.registrarUsuario(wendel);
		Usuario wenzel = new Usuario("wenzel@pizarrello.net", "Wenzel");
		sitio.registrarUsuario(wenzel);
		Usuario werner = new Usuario("werner@pizarrello.net", "Werner");
		sitio.registrarUsuario(werner);
		Usuario wilfried = new Usuario("wilfried@pizarrello.net", "Wilfried");
		sitio.registrarUsuario(wilfried);
		Usuario wilhelm = new Usuario("wilhelm@pizarrello.net", "Wilhelm");
		sitio.registrarUsuario(wilhelm);
		Usuario wolfgang = new Usuario("wolfgang@pizarrello.net", "Wolfgang");
		sitio.registrarUsuario(wolfgang);
		Usuario wolfram = new Usuario("wolfram@pizarrello.net", "Wolfram");
		sitio.registrarUsuario(wolfram);
		Proyecto proyecto363 = new Proyecto(wolfgang);
		proyecto363.agregarAdministrador(wolfgang);
		proyecto363.agregarColaborador(hugo);
		proyecto363.agregarColaborador(bruno);
		proyecto363.agregarColaborador(florian);
		Pizarra backlogproyecto363 = new Pizarra("backlogproyecto363");
		TareaDeDesarrollo start_publishing_dates =  new TareaDeDesarrollo("start publishing dates", format.parse("3/2/2015"));
		start_publishing_dates.setRequerimientos("As a site editor, I can set start publishing dates (when teaser appears on front page), old article date (when it disappears from home page), and stop publishing dates (when it's removed from site, if ever) for articles.");
		backlogproyecto363.agregarTarea(start_publishing_dates);
		TareaDeInvestigacion comprobar_ac =  new TareaDeInvestigacion("comprobar ac", format.parse("15/3/2014"));
		comprobar_ac.setHipotesis("Donec id elit non mi porta gravida at eget metus.");
		comprobar_ac.setResultado("Aenean lacinia bibendum nulla sed consectetur.");
		backlogproyecto363.agregarTarea(comprobar_ac);
		TareaDeDesarrollo what_is_scrum =  new TareaDeDesarrollo("what is scrum", format.parse("27/2/2014"));
		what_is_scrum.setRequerimientos("As a site editor, I can create the content of the What Is Scrum section.");
		backlogproyecto363.agregarTarea(what_is_scrum);
		proyecto363.agregarPizarra(backlogproyecto363);
		Pizarra doingproyecto363 = new Pizarra("doingproyecto363");
		TareaDeDesarrollo other_course =  new TareaDeDesarrollo("other course", format.parse("16/3/2014"));
		other_course.setRequerimientos("As a site administrator, I can create an Other Course (?) or Event that is not charged a listing fee. This is so that the Scrum Alliance doesn’t charge itself for Scrum Gatherings that it puts on.");
		doingproyecto363.agregarTarea(other_course);
		TareaDeInvestigacion comprobar_b =  new TareaDeInvestigacion("comprobar b", format.parse("11/1/2015"));
		comprobar_b.setHipotesis("Sed posuere consectetur est at lobortis.");
		comprobar_b.setResultado("Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.");
		doingproyecto363.agregarTarea(comprobar_b);
		TareaDeInvestigacion comprobar_z =  new TareaDeInvestigacion("comprobar z", format.parse("16/2/2014"));
		comprobar_z.setHipotesis("Pellentesque ornare sem lacinia quam venenatis vestibulum.");
		comprobar_z.setResultado("Donec sed odio dui.");
		doingproyecto363.agregarTarea(comprobar_z);
		TareaDeDesarrollo welcome_scrum_alliance =  new TareaDeDesarrollo("welcome scrum alliance", format.parse("6/3/2015"));
		welcome_scrum_alliance.setRequerimientos("As a new Certified ScrumMaster or Certified Product Owner, once my name has been loaded to the registry I am sent an email welcoming me to the Scrum Alliance and containing instructions on how to register / activate my membership.");
		doingproyecto363.agregarTarea(welcome_scrum_alliance);
		TareaDeDesarrollo short_term_mem_problems =  new TareaDeDesarrollo("short term mem problems", format.parse("25/2/2015"));
		short_term_mem_problems.setRequerimientos("As a member with short-term memory problems, I can have the system email me a new password or a password reminder, possibly my username (unless we use email for that), and As a trainer, I can read information of relevance only to trainers.");
		doingproyecto363.agregarTarea(short_term_mem_problems);
		proyecto363.agregarPizarra(doingproyecto363);
		Pizarra doneproyecto363 = new Pizarra("doneproyecto363");
		TareaDeDesarrollo teaser =  new TareaDeDesarrollo("teaser", format.parse("13/2/2014"));
		teaser.setRequerimientos("As the site editor, I can include a teaser with each article. The teaser shows up on the front page for all to read.");
		doneproyecto363.agregarTarea(teaser);
		TareaDeInvestigacion comprobar_c =  new TareaDeInvestigacion("comprobar c", format.parse("2/3/2014"));
		comprobar_c.setHipotesis("Donec id elit non mi porta gravida at eget metus.");
		comprobar_c.setResultado("Aenean lacinia bibendum nulla sed consectetur.");
		doneproyecto363.agregarTarea(comprobar_c);
		TareaDeDesarrollo search_faqs =  new TareaDeDesarrollo("search faqs", format.parse("21/1/2015"));
		search_faqs.setRequerimientos("As a site member, I can do a full-text search of the FAQs. (Maybe we want this for any site visitor?)");
		doneproyecto363.agregarTarea(search_faqs);
		TareaDeDesarrollo pay_anual_fee =  new TareaDeDesarrollo("pay anual fee", format.parse("4/3/2014"));
		pay_anual_fee.setRequerimientos("As someone about to become a trainer, I can pay an annual fee.");
		doneproyecto363.agregarTarea(pay_anual_fee);
		TareaDeInvestigacion comprobar_a =  new TareaDeInvestigacion("comprobar a", format.parse("20/1/2015"));
		comprobar_a.setHipotesis("Cras justo odio, dapibus ac facilisis in, egestas eget quam.");
		comprobar_a.setResultado("Etiam porta sem malesuada magna mollis euismod.");
		doneproyecto363.agregarTarea(comprobar_a);
		proyecto363.agregarPizarra(doneproyecto363);
		sitio.agregarProyecto(proyecto363);
		backlogproyecto363.moverTareaAPizarra(comprobar_ac, doneproyecto363);
		backlogproyecto363.moverTareaAPizarra(start_publishing_dates, doneproyecto363);
		doingproyecto363.moverTareaAPizarra(short_term_mem_problems, backlogproyecto363);
		doneproyecto363.moverTareaAPizarra(comprobar_a, backlogproyecto363);
		doingproyecto363.moverTareaAPizarra(other_course, backlogproyecto363);
		Proyecto proyecto8149 = new Proyecto(kristian);
		proyecto8149.agregarAdministrador(kristian);
		proyecto8149.agregarAdministrador(mario);
		proyecto8149.agregarAdministrador(oskar);
		proyecto8149.agregarColaborador(leopold);
		proyecto8149.agregarColaborador(helmut);
		Pizarra backlogproyecto8149 = new Pizarra("backlogproyecto8149");
		TareaDeDesarrollo view_all_pending_classes =  new TareaDeDesarrollo("view all pending classes", format.parse("25/2/2014"));
		view_all_pending_classes.setRequerimientos("As a site admin, I can view all classes in a pending state.");
		backlogproyecto8149.agregarTarea(view_all_pending_classes);
		TareaDeInvestigacion comprobar_y =  new TareaDeInvestigacion("comprobar y", format.parse("25/2/2014"));
		comprobar_y.setHipotesis("Maecenas faucibus mollis interdum.");
		comprobar_y.setResultado("Aenean eu leo quam.");
		backlogproyecto8149.agregarTarea(comprobar_y);
		TareaDeDesarrollo download_presentations =  new TareaDeDesarrollo("download presentations", format.parse("27/2/2015"));
		download_presentations.setRequerimientos("As a visitor, I can download presentations, PDFs, etc. on Scrum that I can use.");
		backlogproyecto8149.agregarTarea(download_presentations);
		proyecto8149.agregarPizarra(backlogproyecto8149);
		Pizarra doingproyecto8149 = new Pizarra("doingproyecto8149");
		TareaDeDesarrollo profile_details =  new TareaDeDesarrollo("profile details", format.parse("8/2/2014"));
		profile_details.setRequerimientos("As a Practitioner, I want my profile page to include additional details about me (i.e., some of the answers to my Practitioner application).");
		doingproyecto8149.agregarTarea(profile_details);
		TareaDeDesarrollo upcoming_courses =  new TareaDeDesarrollo("upcoming courses", format.parse("9/3/2015"));
		upcoming_courses.setRequerimientos("As a site member, the upcoming courses are what I want visitors to notice.");
		doingproyecto8149.agregarTarea(upcoming_courses);
		TareaDeInvestigacion comprobar_r =  new TareaDeInvestigacion("comprobar r", format.parse("11/1/2015"));
		comprobar_r.setHipotesis("Maecenas faucibus mollis interdum.");
		comprobar_r.setResultado("Morbi leo risus, porta ac consectetur ac, vestibulum at eros.");
		doingproyecto8149.agregarTarea(comprobar_r);
		TareaDeDesarrollo read_some_articles =  new TareaDeDesarrollo("read some articles", format.parse("12/2/2014"));
		read_some_articles.setRequerimientos("As a site visitor, I want to be able to read some of your articles.");
		doingproyecto8149.agregarTarea(read_some_articles);
		TareaDeDesarrollo maintain_faqs =  new TareaDeDesarrollo("maintain faqs", format.parse("18/3/2015"));
		maintain_faqs.setRequerimientos("As a site editor, I can maintain an FAQ section.");
		doingproyecto8149.agregarTarea(maintain_faqs);
		proyecto8149.agregarPizarra(doingproyecto8149);
		Pizarra doneproyecto8149 = new Pizarra("doneproyecto8149");
		TareaDeDesarrollo subscribe_visitor =  new TareaDeDesarrollo("subscribe visitor", format.parse("10/3/2014"));
		subscribe_visitor.setRequerimientos("As a site visitor, I can subscribe to an RSS feed of articles. (Teasers only?)");
		doneproyecto8149.agregarTarea(subscribe_visitor);
		TareaDeInvestigacion comprobar_o =  new TareaDeInvestigacion("comprobar o", format.parse("7/3/2015"));
		comprobar_o.setHipotesis("Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.");
		comprobar_o.setResultado("Cras mattis consectetur purus sit amet fermentum.");
		doneproyecto8149.agregarTarea(comprobar_o);
		TareaDeDesarrollo flexibility_content =  new TareaDeDesarrollo("flexibility content", format.parse("9/3/2014"));
		flexibility_content.setRequerimientos("As a site editor, I'd like to have some flexibility as to where things appear to accommodate different types of content.");
		doneproyecto8149.agregarTarea(flexibility_content);
		TareaDeDesarrollo indicate_publicly_available =  new TareaDeDesarrollo("indicate publicly available", format.parse("12/3/2014"));
		indicate_publicly_available.setRequerimientos("As a site editor, I want to be able to indicate whether an article is publicly available or for members only.");
		doneproyecto8149.agregarTarea(indicate_publicly_available);
		TareaDeDesarrollo prominent_area =  new TareaDeDesarrollo("prominent area", format.parse("19/1/2015"));
		prominent_area.setRequerimientos("As a site editor, I want to have a prominent area on the home page where I can put special announcements, not necessarily news or articles.");
		doneproyecto8149.agregarTarea(prominent_area);
		proyecto8149.agregarPizarra(doneproyecto8149);
		sitio.agregarProyecto(proyecto8149);
		backlogproyecto8149.moverTareaAPizarra(download_presentations, doneproyecto8149);
		doneproyecto8149.moverTareaAPizarra(indicate_publicly_available, doingproyecto8149);
		doingproyecto8149.moverTareaAPizarra(comprobar_r, doneproyecto8149);
		doingproyecto8149.moverTareaAPizarra(upcoming_courses, backlogproyecto8149);
		Proyecto proyecto587 = new Proyecto(christof);
		proyecto587.agregarAdministrador(christof);
		proyecto587.agregarAdministrador(ingemar);
		proyecto587.agregarAdministrador(thomas);
		proyecto587.agregarColaborador(ambros);
		proyecto587.agregarAdministrador(laurenz);
		proyecto587.agregarAdministrador(lukas);
		proyecto587.agregarAdministrador(simon);
		proyecto587.agregarAdministrador(clemens);
		proyecto587.agregarAdministrador(karsten);
		Pizarra backlogproyecto587 = new Pizarra("backlogproyecto587");
		TareaDeDesarrollo send_email =  new TareaDeDesarrollo("send email", format.parse("1/1/2014"));
		send_email.setRequerimientos("As a site member, I can send an email to any member via a form.");
		backlogproyecto587.agregarTarea(send_email);
		TareaDeDesarrollo extend_an_ad =  new TareaDeDesarrollo("extend an ad", format.parse("23/1/2015"));
		extend_an_ad.setRequerimientos("As someone who wants to hire, I want to be able to extend an ad for another 30 days (repeatedly) by visiting the site and updating the posting. (Note, I can’t update it 10 times today and extend the posting 300 days today.)");
		backlogproyecto587.agregarTarea(extend_an_ad);
		TareaDeDesarrollo delete_course =  new TareaDeDesarrollo("delete course", format.parse("21/3/2015"));
		delete_course.setRequerimientos("As a trainer, I can delete one of my courses or events.");
		backlogproyecto587.agregarTarea(delete_course);
		TareaDeDesarrollo full_access_for_members =  new TareaDeDesarrollo("full access for members", format.parse("2/2/2015"));
		full_access_for_members.setRequerimientos("As a site member, I want to have full access to all articles.");
		backlogproyecto587.agregarTarea(full_access_for_members);
		TareaDeDesarrollo no_submit_answers =  new TareaDeDesarrollo("no submit answers", format.parse("16/1/2015"));
		no_submit_answers.setRequerimientos("As a trainer, I want to be assured that no one can submit the same answers multiple time and skew my results.");
		backlogproyecto587.agregarTarea(no_submit_answers);
		proyecto587.agregarPizarra(backlogproyecto587);
		Pizarra doingproyecto587 = new Pizarra("doingproyecto587");
		TareaDeInvestigacion comprobar_k =  new TareaDeInvestigacion("comprobar k", format.parse("9/3/2014"));
		comprobar_k.setHipotesis("Donec ullamcorper nulla non metus auctor fringilla.");
		comprobar_k.setResultado("Donec ullamcorper nulla non metus auctor fringilla.");
		doingproyecto587.agregarTarea(comprobar_k);
		TareaDeDesarrollo homepage_logo_sponsor =  new TareaDeDesarrollo("homepage logo sponsor", format.parse("12/1/2015"));
		homepage_logo_sponsor.setRequerimientos("As a corporate sponsor I want my logo to randomly appear on the home page. (That is, it rotates among other corporate sponsors.)");
		doingproyecto587.agregarTarea(homepage_logo_sponsor);
		TareaDeInvestigacion comprobar_g =  new TareaDeInvestigacion("comprobar g", format.parse("2/3/2014"));
		comprobar_g.setHipotesis("Maecenas faucibus mollis interdum.");
		comprobar_g.setResultado("Morbi leo risus, porta ac consectetur ac, vestibulum at eros.");
		doingproyecto587.agregarTarea(comprobar_g);
		TareaDeDesarrollo tease_entire_article =  new TareaDeDesarrollo("tease entire article", format.parse("2/2/2014"));
		tease_entire_article.setRequerimientos("As a site member who has read a teaser on the front page, I want to read the entire article. (Note: We want any site visitor to read articles for now.)");
		doingproyecto587.agregarTarea(tease_entire_article);
		proyecto587.agregarPizarra(doingproyecto587);
		Pizarra doneproyecto587 = new Pizarra("doneproyecto587");
		TareaDeDesarrollo mark_private_profile =  new TareaDeDesarrollo("mark private profile", format.parse("19/1/2014"));
		mark_private_profile.setRequerimientos("As a site member, I can mark my profile as private in which case only my name will appear.");
		doneproyecto587.agregarTarea(mark_private_profile);
		TareaDeDesarrollo edit_profiles =  new TareaDeDesarrollo("edit profiles", format.parse("12/3/2014"));
		edit_profiles.setRequerimientos("As a site administrator, I can edit any site member profile.");
		doneproyecto587.agregarTarea(edit_profiles);
		TareaDeDesarrollo full_text_search =  new TareaDeDesarrollo("full text search", format.parse("20/1/2014"));
		full_text_search.setRequerimientos("As a site visitor, I can do a full-text search of article body, title, and author name.");
		doneproyecto587.agregarTarea(full_text_search);
		proyecto587.agregarPizarra(doneproyecto587);
		sitio.agregarProyecto(proyecto587);
		doneproyecto587.moverTareaAPizarra(mark_private_profile, backlogproyecto587);
		backlogproyecto587.moverTareaAPizarra(mark_private_profile, doingproyecto587);
		doingproyecto587.moverTareaAPizarra(comprobar_k, backlogproyecto587);
		doneproyecto587.moverTareaAPizarra(full_text_search, backlogproyecto587);
		doneproyecto587.moverTareaAPizarra(edit_profiles, doingproyecto587);
		backlogproyecto587.moverTareaAPizarra(delete_course, doingproyecto587);
		Proyecto proyecto2997 = new Proyecto(erhard);
		proyecto2997.agregarAdministrador(erhard);
		proyecto2997.agregarAdministrador(heinrich);
		proyecto2997.agregarColaborador(felix);
		proyecto2997.agregarAdministrador(erwin);
		proyecto2997.agregarColaborador(berthold);
		proyecto2997.agregarColaborador(rudolf);
		proyecto2997.agregarAdministrador(fabian);
		Pizarra backlogproyecto2997 = new Pizarra("backlogproyecto2997");
		TareaDeDesarrollo read_faqs =  new TareaDeDesarrollo("read faqs", format.parse("9/2/2015"));
		read_faqs.setRequerimientos("As a site visitor, I can read FAQs.");
		backlogproyecto2997.agregarTarea(read_faqs);
		TareaDeInvestigacion comprobar_t =  new TareaDeInvestigacion("comprobar t", format.parse("28/2/2015"));
		comprobar_t.setHipotesis("Aenean eu leo quam.");
		comprobar_t.setResultado("Pellentesque ornare sem lacinia quam venenatis vestibulum.");
		backlogproyecto2997.agregarTarea(comprobar_t);
		TareaDeDesarrollo fill_out_app =  new TareaDeDesarrollo("fill out app", format.parse("13/1/2015"));
		fill_out_app.setRequerimientos("As a site member, I can fill out an application to become a Practitioner.");
		backlogproyecto2997.agregarTarea(fill_out_app);
		proyecto2997.agregarPizarra(backlogproyecto2997);
		Pizarra doingproyecto2997 = new Pizarra("doingproyecto2997");
		TareaDeInvestigacion comprobar_q =  new TareaDeInvestigacion("comprobar q", format.parse("17/1/2015"));
		comprobar_q.setHipotesis("Maecenas faucibus mollis interdum.");
		comprobar_q.setResultado("Nulla vitae elit libero, a pharetra augue.");
		doingproyecto2997.agregarTarea(comprobar_q);
		TareaDeInvestigacion comprobar_v =  new TareaDeInvestigacion("comprobar v", format.parse("27/2/2015"));
		comprobar_v.setHipotesis("Integer posuere erat a ante venenatis dapibus posuere velit aliquet.");
		comprobar_v.setResultado("Maecenas faucibus mollis interdum.");
		doingproyecto2997.agregarTarea(comprobar_v);
		TareaDeDesarrollo certification_course =  new TareaDeDesarrollo("certification course", format.parse("11/1/2015"));
		certification_course.setRequerimientos("As someone who successfully completed a Certification Course (becoming a Certified ScrumMaster or Certified Product Owner), I am emailed a link to a survey about the course and instructor.");
		doingproyecto2997.agregarTarea(certification_course);
		TareaDeDesarrollo turn_course_to_event =  new TareaDeDesarrollo("turn course to event", format.parse("26/1/2015"));
		turn_course_to_event.setRequerimientos("As a trainer, admin, or editor, I can turn a course into an event or an event into a course (in case it was entered in the wrong category). (Note: making something a Certification Course will probably require selecting the name of the course from the pre-approved list.)");
		doingproyecto2997.agregarTarea(turn_course_to_event);
		TareaDeDesarrollo averages_class =  new TareaDeDesarrollo("averages class", format.parse("15/1/2015"));
		averages_class.setRequerimientos("As a site admin, I can see the results for each trainer and averages for the class (for all trainers).");
		doingproyecto2997.agregarTarea(averages_class);
		proyecto2997.agregarPizarra(doingproyecto2997);
		Pizarra doneproyecto2997 = new Pizarra("doneproyecto2997");
		TareaDeDesarrollo notify_results =  new TareaDeDesarrollo("notify results", format.parse("11/1/2015"));
		notify_results.setRequerimientos("As a trainer, I am notified about the results of surveys about my classes. (Questions: After each survey? After a set period of time? Does the trainer get an email or just know to go to the site?)");
		doneproyecto2997.agregarTarea(notify_results);
		TareaDeDesarrollo describe_page =  new TareaDeDesarrollo("describe page", format.parse("11/1/2015"));
		describe_page.setRequerimientos("As a site member, I want to describe myself on my own page in a semi-structured way. That is, I can fill in predefined fields, but also have room for a free-text field or two. (It would be nice to let this free text be HTML or similar.)");
		doneproyecto2997.agregarTarea(describe_page);
		TareaDeDesarrollo popular_items =  new TareaDeDesarrollo("popular items", format.parse("17/3/2015"));
		popular_items.setRequerimientos("As a site visitor, I want to see a list of the most popular items on the site. (Note: Not everything has to be considered. For example, we don’t need to know the most popular profile but it would be useful to a have a \"most popular\" box that listed the most popular articles, news items, or etc.)");
		doneproyecto2997.agregarTarea(popular_items);
		TareaDeDesarrollo prioritiz =  new TareaDeDesarrollo("prioritiz", format.parse("24/2/2015"));
		prioritiz.setRequerimientos("As a site editor, I can assign priority numbers to news items. Items are displayed on the front page based on priority.");
		doneproyecto2997.agregarTarea(prioritiz);
		TareaDeDesarrollo subscribe_rss_jobs =  new TareaDeDesarrollo("subscribe rss jobs", format.parse("11/3/2015"));
		subscribe_rss_jobs.setRequerimientos("As a site member, I can subscribe to an RSS feed of jobs available.");
		doneproyecto2997.agregarTarea(subscribe_rss_jobs);
		proyecto2997.agregarPizarra(doneproyecto2997);
		sitio.agregarProyecto(proyecto2997);
		backlogproyecto2997.moverTareaAPizarra(comprobar_t, doneproyecto2997);
		doneproyecto2997.moverTareaAPizarra(notify_results, backlogproyecto2997);
		doingproyecto2997.moverTareaAPizarra(comprobar_q, doneproyecto2997);
		doneproyecto2997.moverTareaAPizarra(comprobar_q, doingproyecto2997);
		backlogproyecto2997.moverTareaAPizarra(notify_results, doneproyecto2997);
		backlogproyecto2997.moverTareaAPizarra(read_faqs, doneproyecto2997);
		doneproyecto2997.moverTareaAPizarra(popular_items, backlogproyecto2997);
		Proyecto proyecto3782 = new Proyecto(axel);
		proyecto3782.agregarAdministrador(axel);
		proyecto3782.agregarAdministrador(jorg);
		proyecto3782.agregarColaborador(jens);
		proyecto3782.agregarColaborador(bernhard);
		proyecto3782.agregarColaborador(karlheinz);
		Pizarra backlogproyecto3782 = new Pizarra("backlogproyecto3782");
		TareaDeDesarrollo move_people =  new TareaDeDesarrollo("move people", format.parse("2/3/2014"));
		move_people.setRequerimientos("As a site admin who has received proof of payment from a trainer, I can move people in his or her class from a pending state to the registry.");
		backlogproyecto3782.agregarTarea(move_people);
		TareaDeDesarrollo jobs_stop_publishing =  new TareaDeDesarrollo("jobs stop publishing", format.parse("12/1/2015"));
		jobs_stop_publishing.setRequerimientos("As a site admin, I want jobs to stop publishing on the site 30 days after being posted. (Note: 30 days doesn’t need to be configurable at this point. Hardcoding is fine for now.)");
		backlogproyecto3782.agregarTarea(jobs_stop_publishing);
		TareaDeDesarrollo join_sa_fee =  new TareaDeDesarrollo("join sa fee", format.parse("3/3/2014"));
		join_sa_fee.setRequerimientos("As a company, I can join the Scrum Alliance by paying a corporate membership fee. This will include uploading items related to corporate membership (e.g., company description, a logo of size x by y).");
		backlogproyecto3782.agregarTarea(join_sa_fee);
		proyecto3782.agregarPizarra(backlogproyecto3782);
		Pizarra doingproyecto3782 = new Pizarra("doingproyecto3782");
		TareaDeDesarrollo trainer_rating =  new TareaDeDesarrollo("trainer rating", format.parse("2/3/2014"));
		trainer_rating.setRequerimientos("As a site visitor who is considering attending a certification course, I want to see a trainer’s rating (either for that course or for all of his or her certification courses combined).");
		doingproyecto3782.agregarTarea(trainer_rating);
		TareaDeInvestigacion comprobar_ak =  new TareaDeInvestigacion("comprobar ak", format.parse("20/1/2014"));
		comprobar_ak.setHipotesis("Donec ullamcorper nulla non metus auctor fringilla.");
		comprobar_ak.setResultado("Donec ullamcorper nulla non metus auctor fringilla.");
		doingproyecto3782.agregarTarea(comprobar_ak);
		TareaDeDesarrollo rating_show_up =  new TareaDeDesarrollo("rating show up", format.parse("7/3/2014"));
		rating_show_up.setRequerimientos("As a trainer, I want my rating to show up on my profile page.");
		doingproyecto3782.agregarTarea(rating_show_up);
		TareaDeDesarrollo basics_of_scrum =  new TareaDeDesarrollo("basics of Scrum", format.parse("1/3/2014"));
		basics_of_scrum.setRequerimientos("As a site visitor, I want there to be a section of the website that teaches me the basics of what Scrum is.");
		doingproyecto3782.agregarTarea(basics_of_scrum);
		proyecto3782.agregarPizarra(doingproyecto3782);
		Pizarra doneproyecto3782 = new Pizarra("doneproyecto3782");
		TareaDeDesarrollo email_news =  new TareaDeDesarrollo("email news", format.parse("6/2/2015"));
		email_news.setRequerimientos("As a site visitor, I can email news items to the editor. (Note: this could just be an email link to the editor.)");
		doneproyecto3782.agregarTarea(email_news);
		TareaDeDesarrollo listed_registry =  new TareaDeDesarrollo("listed registry", format.parse("26/2/2015"));
		listed_registry.setRequerimientos("As a CSM, Practitioner, or Certified Product Owner, I can have my name listed in the registry without becoming a member of the site. (For example, I take a certification class but never register or let my membership lapse.)");
		doneproyecto3782.agregarTarea(listed_registry);
		TareaDeInvestigacion comprobar_n =  new TareaDeInvestigacion("comprobar n", format.parse("13/1/2014"));
		comprobar_n.setHipotesis("Donec id elit non mi porta gravida at eget metus.");
		comprobar_n.setResultado("Aenean lacinia bibendum nulla sed consectetur.");
		doneproyecto3782.agregarTarea(comprobar_n);
		TareaDeDesarrollo fill_trainer_app =  new TareaDeDesarrollo("fill trainer app", format.parse("10/2/2015"));
		fill_trainer_app.setRequerimientos("As a site member, I can fill out an application to become a Trainer.");
		doneproyecto3782.agregarTarea(fill_trainer_app);
		proyecto3782.agregarPizarra(doneproyecto3782);
		sitio.agregarProyecto(proyecto3782);
		backlogproyecto3782.moverTareaAPizarra(jobs_stop_publishing, doneproyecto3782);
		doneproyecto3782.moverTareaAPizarra(email_news, backlogproyecto3782);
		backlogproyecto3782.moverTareaAPizarra(join_sa_fee, doneproyecto3782);
		proyecto3782.archivarPizarra(backlogproyecto3782);
		Proyecto proyecto9981 = new Proyecto(rudiger);
		proyecto9981.agregarAdministrador(rudiger);
		proyecto9981.agregarAdministrador(jan);
		proyecto9981.agregarAdministrador(andreas);
		proyecto9981.agregarAdministrador(arnulf);
		proyecto9981.agregarColaborador(raimund);
		proyecto9981.agregarAdministrador(herbert);
		proyecto9981.agregarAdministrador(egon);
		Pizarra backlogproyecto9981 = new Pizarra("backlogproyecto9981");
		TareaDeDesarrollo content_for_visitor =  new TareaDeDesarrollo("content for visitor", format.parse("27/2/2015"));
		content_for_visitor.setRequerimientos("As a site visitor, I want to see new content when I come to the site.");
		backlogproyecto9981.agregarTarea(content_for_visitor);
		TareaDeInvestigacion comprobar_p =  new TareaDeInvestigacion("comprobar p", format.parse("12/1/2015"));
		comprobar_p.setHipotesis("Etiam porta sem malesuada magna mollis euismod.");
		comprobar_p.setResultado("Integer posuere erat a ante venenatis dapibus posuere velit aliquet.");
		backlogproyecto9981.agregarTarea(comprobar_p);
		TareaDeDesarrollo prifile_trainer_details =  new TareaDeDesarrollo("prifile trainer details", format.parse("4/3/2015"));
		prifile_trainer_details.setRequerimientos("As a Trainer, I want my profile page to include additional details about me (i.e., some of the answers to my Trainer application).");
		backlogproyecto9981.agregarTarea(prifile_trainer_details);
		TareaDeDesarrollo delete_events =  new TareaDeDesarrollo("delete events", format.parse("9/2/2014"));
		delete_events.setRequerimientos("As a site admin, I can delete any course or event.");
		backlogproyecto9981.agregarTarea(delete_events);
		TareaDeDesarrollo subscribe =  new TareaDeDesarrollo("subscribe", format.parse("25/1/2015"));
		subscribe.setRequerimientos("As a site member, I can subscribe to an RSS feed of news (and events? Or are they separate?).");
		backlogproyecto9981.agregarTarea(subscribe);
		proyecto9981.agregarPizarra(backlogproyecto9981);
		Pizarra doingproyecto9981 = new Pizarra("doingproyecto9981");
		TareaDeDesarrollo glance_home =  new TareaDeDesarrollo("glance home", format.parse("22/2/2015"));
		glance_home.setRequerimientos("As a site visitor, I want to know as I glance around the home page what on earth a CSM is and why I'd want to be one.");
		doingproyecto9981.agregarTarea(glance_home);
		TareaDeDesarrollo mark_address =  new TareaDeDesarrollo("mark address", format.parse("2/2/2015"));
		mark_address.setRequerimientos("As a site member, I can mark my email address as private even if the rest of my profile is not.");
		doingproyecto9981.agregarTarea(mark_address);
		TareaDeDesarrollo set_listing_fee =  new TareaDeDesarrollo("set listing fee", format.parse("15/3/2015"));
		set_listing_fee.setRequerimientos("As a site administrator, I can set the listing fee per Other Course or Event.");
		doingproyecto9981.agregarTarea(set_listing_fee);
		TareaDeDesarrollo link_from_article =  new TareaDeDesarrollo("link from article", format.parse("11/3/2014"));
		link_from_article.setRequerimientos("As a site visitor, I want the link from the article teaser to take me directly to the body of the article... not to another teaser setup.");
		doingproyecto9981.agregarTarea(link_from_article);
		TareaDeDesarrollo scrum_visitor =  new TareaDeDesarrollo("scrum visitor", format.parse("21/1/2015"));
		scrum_visitor.setRequerimientos("As a site visitor, I need to know as soon as I visit what on earth Scrum is, and why it needs an alliance.");
		doingproyecto9981.agregarTarea(scrum_visitor);
		proyecto9981.agregarPizarra(doingproyecto9981);
		Pizarra doneproyecto9981 = new Pizarra("doneproyecto9981");
		TareaDeDesarrollo post_info_for_trainers =  new TareaDeDesarrollo("post info for trainers", format.parse("27/3/2014"));
		post_info_for_trainers.setRequerimientos("As a site editor, I can post information in a trainers-only section.");
		doneproyecto9981.agregarTarea(post_info_for_trainers);
		TareaDeInvestigacion comprobar_ah =  new TareaDeInvestigacion("comprobar ah", format.parse("22/1/2015"));
		comprobar_ah.setHipotesis("Aenean lacinia bibendum nulla sed consectetur.");
		comprobar_ah.setResultado("Maecenas faucibus mollis interdum.");
		doneproyecto9981.agregarTarea(comprobar_ah);
		TareaDeDesarrollo update_events =  new TareaDeDesarrollo("update events", format.parse("9/1/2015"));
		update_events.setRequerimientos("As a site editor, I can update any course or event.");
		doneproyecto9981.agregarTarea(update_events);
		TareaDeDesarrollo fill_form_search =  new TareaDeDesarrollo("fill form search", format.parse("25/3/2015"));
		fill_form_search.setRequerimientos("As a site visitor, I have an advanced search option that lets me fill in a form of search criteria (country, state, trainer name, date range, word in description, etc.).");
		doneproyecto9981.agregarTarea(fill_form_search);
		TareaDeDesarrollo post_comments_articles =  new TareaDeDesarrollo("post comments articles", format.parse("28/2/2015"));
		post_comments_articles.setRequerimientos("As a site visitor, I can post comments about articles so that others can read them.");
		doneproyecto9981.agregarTarea(post_comments_articles);
		proyecto9981.agregarPizarra(doneproyecto9981);
		sitio.agregarProyecto(proyecto9981);
		doingproyecto9981.moverTareaAPizarra(glance_home, backlogproyecto9981);
		doingproyecto9981.moverTareaAPizarra(scrum_visitor, doneproyecto9981);
		doingproyecto9981.moverTareaAPizarra(mark_address, backlogproyecto9981);
		doingproyecto9981.moverTareaAPizarra(set_listing_fee, doneproyecto9981);
		Proyecto proyecto821 = new Proyecto(golo);
		proyecto821.agregarAdministrador(golo);
		proyecto821.agregarAdministrador(hans);
		proyecto821.agregarAdministrador(erhard);
		Pizarra backlogproyecto821 = new Pizarra("backlogproyecto821");
		TareaDeInvestigacion comprobar_i =  new TareaDeInvestigacion("comprobar i", format.parse("12/3/2015"));
		comprobar_i.setHipotesis("Aenean eu leo quam.");
		comprobar_i.setResultado("Pellentesque ornare sem lacinia quam venenatis vestibulum.");
		backlogproyecto821.agregarTarea(comprobar_i);
		TareaDeDesarrollo copy_course =  new TareaDeDesarrollo("copy course", format.parse("20/2/2014"));
		copy_course.setRequerimientos("As a trainer, I can copy one of my courses or events so that I can create a new one. When copying it I am asked for the date(s) of the new course or event.");
		backlogproyecto821.agregarTarea(copy_course);
		TareaDeDesarrollo charge_fee_csm_cpo =  new TareaDeDesarrollo("charge fee csm cpo", format.parse("27/2/2015"));
		charge_fee_csm_cpo.setRequerimientos("As a CSM or CPO who has been approved for Practitioner status (by a site admin reading my submission), I am charged a fee.");
		backlogproyecto821.agregarTarea(charge_fee_csm_cpo);
		TareaDeDesarrollo post_help_ad =  new TareaDeDesarrollo("post help ad", format.parse("10/3/2014"));
		post_help_ad.setRequerimientos("As someone who wants to hire, I can post a “help wanted ad”.");
		backlogproyecto821.agregarTarea(post_help_ad);
		TareaDeDesarrollo list_of_courses =  new TareaDeDesarrollo("list of courses", format.parse("13/2/2015"));
		list_of_courses.setRequerimientos("As a site visitor, I can see a list of all upcoming “Certification Courses.” I can page through them if there are a lot.");
		backlogproyecto821.agregarTarea(list_of_courses);
		proyecto821.agregarPizarra(backlogproyecto821);
		Pizarra doingproyecto821 = new Pizarra("doingproyecto821");
		TareaDeDesarrollo search_profiles =  new TareaDeDesarrollo("search profiles", format.parse("9/3/2015"));
		search_profiles.setRequerimientos("As a site member, I can search for profiles based on a few fields (class attended, location, name).");
		doingproyecto821.agregarTarea(search_profiles);
		TareaDeDesarrollo certifications_sm =  new TareaDeDesarrollo("certifications sm", format.parse("3/2/2014"));
		certifications_sm.setRequerimientos("As a site visitor, I can view lists on the site of all Certified ScrumMasters, Practitioners, Trainers, and Certified Product Owners. (The CSM list has over 5,000 names so a letter-based pagination approach is needed.)");
		doingproyecto821.agregarTarea(certifications_sm);
		TareaDeDesarrollo have_interesting_articles =  new TareaDeDesarrollo("have interesting articles", format.parse("17/1/2015"));
		have_interesting_articles.setRequerimientos("As a site visitor, I want to have articles that interest me and are easy to get to.");
		doingproyecto821.agregarTarea(have_interesting_articles);
		TareaDeInvestigacion comprobar_u =  new TareaDeInvestigacion("comprobar u", format.parse("9/3/2014"));
		comprobar_u.setHipotesis("Cras mattis consectetur purus sit amet fermentum.");
		comprobar_u.setResultado("Etiam porta sem malesuada magna mollis euismod.");
		doingproyecto821.agregarTarea(comprobar_u);
		TareaDeDesarrollo edit_delete_help =  new TareaDeDesarrollo("edit delete help", format.parse("22/1/2014"));
		edit_delete_help.setRequerimientos("As a site admin, I can edit and delete help wanted ads.");
		doingproyecto821.agregarTarea(edit_delete_help);
		proyecto821.agregarPizarra(doingproyecto821);
		Pizarra doneproyecto821 = new Pizarra("doneproyecto821");
		TareaDeInvestigacion comprobar_ae =  new TareaDeInvestigacion("comprobar ae", format.parse("15/3/2014"));
		comprobar_ae.setHipotesis("Etiam porta sem malesuada magna mollis euismod.");
		comprobar_ae.setResultado("Integer posuere erat a ante venenatis dapibus posuere velit aliquet.");
		doneproyecto821.agregarTarea(comprobar_ae);
		TareaDeDesarrollo approve_apps =  new TareaDeDesarrollo("approve apps", format.parse("6/1/2014"));
		approve_apps.setRequerimientos("As a site administrator, I can read practicing and training applications and approve or reject them.");
		doneproyecto821.agregarTarea(approve_apps);
		TareaDeDesarrollo content_to_site =  new TareaDeDesarrollo("content to site", format.parse("24/1/2015"));
		content_to_site.setRequerimientos("As a Practitioner or Trainer, when I provide content to the site I want a small graphic associated with the content indicating I’m a Practitioner or Trainer. (For example, Amazon’s “Top 500 Reviewers” approach.)");
		doneproyecto821.agregarTarea(content_to_site);
		TareaDeDesarrollo read_news =  new TareaDeDesarrollo("read news", format.parse("11/2/2015"));
		read_news.setRequerimientos("As a site visitor, I can read current news on the home page.");
		doneproyecto821.agregarTarea(read_news);
		TareaDeInvestigacion comprobar_d =  new TareaDeInvestigacion("comprobar d", format.parse("26/2/2015"));
		comprobar_d.setHipotesis("Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.");
		comprobar_d.setResultado("Cras mattis consectetur purus sit amet fermentum.");
		doneproyecto821.agregarTarea(comprobar_d);
		proyecto821.agregarPizarra(doneproyecto821);
		sitio.agregarProyecto(proyecto821);
		doneproyecto821.moverTareaAPizarra(read_news, backlogproyecto821);
		doneproyecto821.moverTareaAPizarra(approve_apps, doingproyecto821);
		backlogproyecto821.moverTareaAPizarra(charge_fee_csm_cpo, doingproyecto821);
		doingproyecto821.moverTareaAPizarra(comprobar_u, doneproyecto821);
		backlogproyecto821.moverTareaAPizarra(post_help_ad, doneproyecto821);
		doneproyecto821.moverTareaAPizarra(comprobar_d, backlogproyecto821);
		doneproyecto821.moverTareaAPizarra(content_to_site, backlogproyecto821);
		doingproyecto821.moverTareaAPizarra(edit_delete_help, doneproyecto821);
		Proyecto proyecto5298 = new Proyecto(dominik);
		proyecto5298.agregarAdministrador(dominik);
		proyecto5298.agregarAdministrador(friedrich);
		proyecto5298.agregarAdministrador(hartmut);
		proyecto5298.agregarColaborador(karlheinz);
		proyecto5298.agregarColaborador(georg);
		proyecto5298.agregarColaborador(heinrich);
		proyecto5298.agregarColaborador(engelbert);
		proyecto5298.agregarAdministrador(golo);
		Pizarra backlogproyecto5298 = new Pizarra("backlogproyecto5298");
		TareaDeInvestigacion comprobar_ab =  new TareaDeInvestigacion("comprobar ab", format.parse("25/2/2014"));
		comprobar_ab.setHipotesis("Sed posuere consectetur est at lobortis.");
		comprobar_ab.setResultado("Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.");
		backlogproyecto5298.agregarTarea(comprobar_ab);
		TareaDeDesarrollo approve_help =  new TareaDeDesarrollo("approve help", format.parse("10/1/2014"));
		approve_help.setRequerimientos("As a site admin, I need to approve each help wanted ad before it gets to the site.");
		backlogproyecto5298.agregarTarea(approve_help);
		proyecto5298.agregarPizarra(backlogproyecto5298);
		Pizarra doingproyecto5298 = new Pizarra("doingproyecto5298");
		TareaDeInvestigacion comprobar_f =  new TareaDeInvestigacion("comprobar f", format.parse("8/2/2014"));
		comprobar_f.setHipotesis("Maecenas faucibus mollis interdum.");
		comprobar_f.setResultado("Nulla vitae elit libero, a pharetra augue.");
		doingproyecto5298.agregarTarea(comprobar_f);
		TareaDeInvestigacion comprobar_al =  new TareaDeInvestigacion("comprobar al", format.parse("28/3/2015"));
		comprobar_al.setHipotesis("Aenean lacinia bibendum nulla sed consectetur.");
		comprobar_al.setResultado("Etiam porta sem malesuada magna mollis euismod.");
		doingproyecto5298.agregarTarea(comprobar_al);
		TareaDeDesarrollo date_on_news =  new TareaDeDesarrollo("date on news", format.parse("15/3/2015"));
		date_on_news.setRequerimientos("As a site a site editor, I can set the following dates on a news item: Start Publishing Date, Old News Date, Stop Publishing Date. These dates refer to the date an item becomes visible on the site (perhaps next Monday), the date it stops appearing on the home page, and the date it is removed from the site (which may be never).");
		doingproyecto5298.agregarTarea(date_on_news);
		TareaDeInvestigacion comprobar_h =  new TareaDeInvestigacion("comprobar h", format.parse("7/3/2015"));
		comprobar_h.setHipotesis("Aenean lacinia bibendum nulla sed consectetur.");
		comprobar_h.setResultado("Maecenas faucibus mollis interdum.");
		doingproyecto5298.agregarTarea(comprobar_h);
		TareaDeInvestigacion comprobar_am =  new TareaDeInvestigacion("comprobar am", format.parse("9/1/2014"));
		comprobar_am.setHipotesis("Sed posuere consectetur est at lobortis.");
		comprobar_am.setResultado("Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.");
		doingproyecto5298.agregarTarea(comprobar_am);
		proyecto5298.agregarPizarra(doingproyecto5298);
		Pizarra doneproyecto5298 = new Pizarra("doneproyecto5298");
		TareaDeDesarrollo excel_file =  new TareaDeDesarrollo("excel file", format.parse("2/3/2014"));
		excel_file.setRequerimientos("As a trainer who has finished teaching a Certification class, I can load an Excel file (first name, last name, email) into the site. I am prompted for the trainer names (I may not have trained alone), certification date, and type of certification (i.e., CSM or CPO). The names are loaded into a pending state and not yet added to the registry. (Note: We could have this charge $50 per person right then.)");
		doneproyecto5298.agregarTarea(excel_file);
		TareaDeInvestigacion comprobar_w =  new TareaDeInvestigacion("comprobar w", format.parse("8/3/2014"));
		comprobar_w.setHipotesis("Nulla vitae elit libero, a pharetra augue.");
		comprobar_w.setResultado("Maecenas faucibus mollis interdum.");
		doneproyecto5298.agregarTarea(comprobar_w);
		TareaDeInvestigacion comprobar_e =  new TareaDeInvestigacion("comprobar e", format.parse("3/2/2014"));
		comprobar_e.setHipotesis("Etiam porta sem malesuada magna mollis euismod.");
		comprobar_e.setResultado("Integer posuere erat a ante venenatis dapibus posuere velit aliquet.");
		doneproyecto5298.agregarTarea(comprobar_e);
		TareaDeDesarrollo subscribe_courses_events =  new TareaDeDesarrollo("subscribe courses events", format.parse("9/2/2015"));
		subscribe_courses_events.setRequerimientos("As a site visitor, I can subscribe to an RSS feed of upcoming courses and events.");
		doneproyecto5298.agregarTarea(subscribe_courses_events);
		TareaDeDesarrollo list_events =  new TareaDeDesarrollo("list events", format.parse("14/3/2014"));
		list_events.setRequerimientos("As a site visitor, I can see a list of all upcoming “Events.” (Events are things such as the Scrum Gathering, conferences, free seminars, etc.)");
		doneproyecto5298.agregarTarea(list_events);
		proyecto5298.agregarPizarra(doneproyecto5298);
		sitio.agregarProyecto(proyecto5298);
		backlogproyecto5298.moverTareaAPizarra(comprobar_ab, doingproyecto5298);
		doingproyecto5298.moverTareaAPizarra(comprobar_al, doneproyecto5298);
		backlogproyecto5298.moverTareaAPizarra(approve_help, doingproyecto5298);
		doingproyecto5298.moverTareaAPizarra(comprobar_am, backlogproyecto5298);
		Proyecto proyecto8721 = new Proyecto(leon);
		proyecto8721.agregarAdministrador(leon);
		proyecto8721.agregarAdministrador(carsten);
		proyecto8721.agregarColaborador(eugen);
		proyecto8721.agregarColaborador(lothar);
		proyecto8721.agregarColaborador(elias);
		proyecto8721.agregarColaborador(rupert);
		proyecto8721.agregarAdministrador(gregor);
		proyecto8721.agregarColaborador(christof);
		Pizarra backlogproyecto8721 = new Pizarra("backlogproyecto8721");
		TareaDeDesarrollo look_and_feel_editors =  new TareaDeDesarrollo("look and feel editors", format.parse("8/3/2014"));
		look_and_feel_editors.setRequerimientos("As a site editor, I have ideas on how I want the home page to look and feel.");
		backlogproyecto8721.agregarTarea(look_and_feel_editors);
		TareaDeDesarrollo old_news =  new TareaDeDesarrollo("old news", format.parse("21/2/2014"));
		old_news.setRequerimientos("As a site visitor, I can access old news that is no longer on the home page.");
		backlogproyecto8721.agregarTarea(old_news);
		TareaDeInvestigacion comprobar_x =  new TareaDeInvestigacion("comprobar x", format.parse("16/3/2015"));
		comprobar_x.setHipotesis("Morbi leo risus, porta ac consectetur ac, vestibulum at eros.");
		comprobar_x.setResultado("Aenean lacinia bibendum nulla sed consectetur.");
		backlogproyecto8721.agregarTarea(comprobar_x);
		TareaDeDesarrollo list_of_other_courses =  new TareaDeDesarrollo("list of other courses", format.parse("15/3/2014"));
		list_of_other_courses.setRequerimientos("As a site visitor, I can see a list of all upcoming “Other Courses” (non-certification courses). I can page through them if necessary.");
		backlogproyecto8721.agregarTarea(list_of_other_courses);
		TareaDeDesarrollo update_courses_or_events =  new TareaDeDesarrollo("update courses or events", format.parse("4/1/2014"));
		update_courses_or_events.setRequerimientos("As a trainer, I can update one of my existing courses or events.");
		backlogproyecto8721.agregarTarea(update_courses_or_events);
		proyecto8721.agregarPizarra(backlogproyecto8721);
		Pizarra doingproyecto8721 = new Pizarra("doingproyecto8721");
		TareaDeDesarrollo download_training_material =  new TareaDeDesarrollo("download training material", format.parse("27/2/2015"));
		download_training_material.setRequerimientos("As a site member, I can download the latest training material and methodology PDFs.");
		doingproyecto8721.agregarTarea(download_training_material);
		TareaDeInvestigacion comprobar_af =  new TareaDeInvestigacion("comprobar af", format.parse("23/1/2015"));
		comprobar_af.setHipotesis("Maecenas faucibus mollis interdum.");
		comprobar_af.setResultado("Nulla vitae elit libero, a pharetra augue.");
		doingproyecto8721.agregarTarea(comprobar_af);
		TareaDeDesarrollo email_job =  new TareaDeDesarrollo("email job", format.parse("11/3/2014"));
		email_job.setRequerimientos("As a site admin, I am emailed whenever a job is submitted (so that I am aware of it and can decide if I want to post it).");
		doingproyecto8721.agregarTarea(email_job);
		TareaDeDesarrollo read_new_article =  new TareaDeDesarrollo("read new article", format.parse("13/3/2014"));
		read_new_article.setRequerimientos("As a site visitor, I want to read a new article on the front page about once a week.");
		doingproyecto8721.agregarTarea(read_new_article);
		TareaDeDesarrollo display_logo_sponsor =  new TareaDeDesarrollo("display logo sponsor", format.parse("7/3/2015"));
		display_logo_sponsor.setRequerimientos("As a corporate sponsor, my logo is displayed on a “corporate sponsors” page just like at http://www.agilealliance.org/portal_url/corporatemembers. (Note that the display order on that page is random.)");
		doingproyecto8721.agregarTarea(display_logo_sponsor);
		proyecto8721.agregarPizarra(doingproyecto8721);
		Pizarra doneproyecto8721 = new Pizarra("doneproyecto8721");
		TareaDeDesarrollo see_trainer_profile =  new TareaDeDesarrollo("see trainer profile", format.parse("10/2/2015"));
		see_trainer_profile.setRequerimientos("As a site visitor, when I’m viewing a course I can click on the trainer’s name and be taken to the trainer’s profile.");
		doneproyecto8721.agregarTarea(see_trainer_profile);
		TareaDeDesarrollo add_article_to_site =  new TareaDeDesarrollo("add article to site", format.parse("2/2/2014"));
		add_article_to_site.setRequerimientos("As the site editor, I can add an article to the site.");
		doneproyecto8721.agregarTarea(add_article_to_site);
		TareaDeDesarrollo mail_reminder =  new TareaDeDesarrollo("mail reminder", format.parse("23/1/2014"));
		mail_reminder.setRequerimientos("As someone who has posted an ad that is about to expire, seven days before it expires I want to be emailed a reminder so that I can go extend the ad. (Note: This means the ad could have an expiration date 37 days into the future, which is fine.)");
		doneproyecto8721.agregarTarea(mail_reminder);
		proyecto8721.agregarPizarra(doneproyecto8721);
		sitio.agregarProyecto(proyecto8721);
		doneproyecto8721.moverTareaAPizarra(mail_reminder, doingproyecto8721);
		doingproyecto8721.moverTareaAPizarra(read_new_article, doneproyecto8721);
		doneproyecto8721.moverTareaAPizarra(read_new_article, backlogproyecto8721);
		backlogproyecto8721.moverTareaAPizarra(list_of_other_courses, doneproyecto8721);
		backlogproyecto8721.moverTareaAPizarra(update_courses_or_events, doneproyecto8721);
		Proyecto proyecto7427 = new Proyecto(dominik);
		proyecto7427.agregarAdministrador(dominik);
		proyecto7427.agregarAdministrador(jan);
		proyecto7427.agregarAdministrador(dierk);
		proyecto7427.agregarColaborador(elmar);
		proyecto7427.agregarAdministrador(johann);
		Pizarra backlogproyecto7427 = new Pizarra("backlogproyecto7427");
		TareaDeDesarrollo create_course_or_event =  new TareaDeDesarrollo("create course or event", format.parse("3/1/2014"));
		create_course_or_event.setRequerimientos("As a trainer, I can create a new course or event. This includes the following information: name, description (HTML), trainer names (multiple selection from a list), start date, end date, venue name (HTML) and address, contact name, contact phone, contact email, a link for more information, and a link to register. For a certification course the name of the class is a dropdown list; for others, it is free text.");
		backlogproyecto7427.agregarTarea(create_course_or_event);
		TareaDeInvestigacion comprobar_aa =  new TareaDeInvestigacion("comprobar aa", format.parse("24/1/2015"));
		comprobar_aa.setHipotesis("Cras justo odio, dapibus ac facilisis in, egestas eget quam.");
		comprobar_aa.setResultado("Etiam porta sem malesuada magna mollis euismod.");
		backlogproyecto7427.agregarTarea(comprobar_aa);
		TareaDeInvestigacion comprobar_m =  new TareaDeInvestigacion("comprobar m", format.parse("18/3/2015"));
		comprobar_m.setHipotesis("Sed posuere consectetur est at lobortis.");
		comprobar_m.setResultado("Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.");
		backlogproyecto7427.agregarTarea(comprobar_m);
		TareaDeInvestigacion comprobar_aj =  new TareaDeInvestigacion("comprobar aj", format.parse("11/3/2014"));
		comprobar_aj.setHipotesis("Donec sed odio dui.");
		comprobar_aj.setResultado("Morbi leo risus, porta ac consectetur ac, vestibulum at eros.");
		backlogproyecto7427.agregarTarea(comprobar_aj);
		TareaDeInvestigacion comprobar_ad =  new TareaDeInvestigacion("comprobar ad", format.parse("24/2/2014"));
		comprobar_ad.setHipotesis("Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.");
		comprobar_ad.setResultado("Cras mattis consectetur purus sit amet fermentum.");
		backlogproyecto7427.agregarTarea(comprobar_ad);
		proyecto7427.agregarPizarra(backlogproyecto7427);
		Pizarra doingproyecto7427 = new Pizarra("doingproyecto7427");
		TareaDeDesarrollo edit_content_csm =  new TareaDeDesarrollo("edit content csm", format.parse("11/3/2015"));
		edit_content_csm.setRequerimientos("As a site editor, I can edit the content of the email automatically sent to new Certified ScrumMasters and Product Owners.");
		doingproyecto7427.agregarTarea(edit_content_csm);
		TareaDeDesarrollo expiring_membership =  new TareaDeDesarrollo("expiring membership", format.parse("14/3/2015"));
		expiring_membership.setRequerimientos("As someone whose membership (of any type) is about to expire, I am sent a reminder and a link through which I can renew. (Note: Think about overlapping memberships and prorating.)");
		doingproyecto7427.agregarTarea(expiring_membership);
		TareaDeInvestigacion comprobar_ag =  new TareaDeInvestigacion("comprobar ag", format.parse("4/2/2015"));
		comprobar_ag.setHipotesis("Maecenas faucibus mollis interdum.");
		comprobar_ag.setResultado("Morbi leo risus, porta ac consectetur ac, vestibulum at eros.");
		doingproyecto7427.agregarTarea(comprobar_ag);
		TareaDeDesarrollo view_profiles =  new TareaDeDesarrollo("view profiles", format.parse("18/2/2015"));
		view_profiles.setRequerimientos("As a site member, I can view the profiles of other members.");
		doingproyecto7427.agregarTarea(view_profiles);
		TareaDeDesarrollo back_home =  new TareaDeDesarrollo("back home", format.parse("2/3/2014"));
		back_home.setRequerimientos("As a site visitor, I want to be able to get back to the home page quickly and easily.");
		doingproyecto7427.agregarTarea(back_home);
		proyecto7427.agregarPizarra(doingproyecto7427);
		Pizarra doneproyecto7427 = new Pizarra("doneproyecto7427");
		TareaDeInvestigacion comprobar_ai =  new TareaDeInvestigacion("comprobar ai", format.parse("3/2/2015"));
		comprobar_ai.setHipotesis("Aenean eu leo quam.");
		comprobar_ai.setResultado("Pellentesque ornare sem lacinia quam venenatis vestibulum.");
		doneproyecto7427.agregarTarea(comprobar_ai);
		TareaDeDesarrollo scroll_through_jobs =  new TareaDeDesarrollo("scroll through jobs", format.parse("20/3/2014"));
		scroll_through_jobs.setRequerimientos("As a site member (?), I can scroll through a listing of jobs. (There won’t be enough at first to justify search fields.)");
		doneproyecto7427.agregarTarea(scroll_through_jobs);
		TareaDeInvestigacion comprobar_l =  new TareaDeInvestigacion("comprobar l", format.parse("14/1/2015"));
		comprobar_l.setHipotesis("Aenean lacinia bibendum nulla sed consectetur.");
		comprobar_l.setResultado("Etiam porta sem malesuada magna mollis euismod.");
		doneproyecto7427.agregarTarea(comprobar_l);
		TareaDeDesarrollo control_article_looks =  new TareaDeDesarrollo("control article looks", format.parse("11/3/2014"));
		control_article_looks.setRequerimientos("As the site editor, I have pretty good control over how the article looks (include images and captions, for example).");
		doneproyecto7427.agregarTarea(control_article_looks);
		TareaDeDesarrollo profile_list =  new TareaDeDesarrollo("profile list", format.parse("26/1/2015"));
		profile_list.setRequerimientos("As a trainer, I want my profile to list my upcoming classes and include a link to a detailed page about each.");
		doneproyecto7427.agregarTarea(profile_list);
		proyecto7427.agregarPizarra(doneproyecto7427);
		sitio.agregarProyecto(proyecto7427);
		doneproyecto7427.moverTareaAPizarra(comprobar_l, backlogproyecto7427);
		backlogproyecto7427.moverTareaAPizarra(comprobar_aj, doingproyecto7427);
		doingproyecto7427.moverTareaAPizarra(edit_content_csm, doneproyecto7427);
		doingproyecto7427.moverTareaAPizarra(comprobar_aj, doneproyecto7427);
		doingproyecto7427.moverTareaAPizarra(back_home, backlogproyecto7427);
		doingproyecto7427.moverTareaAPizarra(comprobar_ag, backlogproyecto7427);
		backlogproyecto7427.moverTareaAPizarra(create_course_or_event, doingproyecto7427);
		proyecto7427.archivarPizarra(doingproyecto7427);

		return sitio;
		
	}

}
